package com.gabriel.cadastrodemetas.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class NotaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotaAllPropertiesEquals(Nota expected, Nota actual) {
        assertNotaAutoGeneratedPropertiesEquals(expected, actual);
        assertNotaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotaAllUpdatablePropertiesEquals(Nota expected, Nota actual) {
        assertNotaUpdatableFieldsEquals(expected, actual);
        assertNotaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotaAutoGeneratedPropertiesEquals(Nota expected, Nota actual) {
        assertThat(actual)
            .as("Verify Nota auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotaUpdatableFieldsEquals(Nota expected, Nota actual) {
        assertThat(actual)
            .as("Verify Nota relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getArea()).as("check area").isEqualTo(expected.getArea()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertNotaUpdatableRelationshipsEquals(Nota expected, Nota actual) {
        assertThat(actual)
            .as("Verify Nota relationships")
            .satisfies(a -> assertThat(a.getAluno()).as("check aluno").isEqualTo(expected.getAluno()))
            .satisfies(a -> assertThat(a.getSimulado()).as("check simulado").isEqualTo(expected.getSimulado()));
    }
}
